kind = "mobile"
previewPath = "/"
title = "ZawyaAI"
version = "1.0.0"
id = "artifacts/zawyaai"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19661

[services.development]
run = "pnpm --filter @workspace/zawyaai run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/zawyaai", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/zawyaai", "run", "serve" ]

[services.env]
PORT = "19661"
BASE_PATH = "/"
